#!/usr/bin/env bash
# Deterministic stand-in for the PrusaSlicer CLI, used by the golden tests so
# print_plan.json is byte-identical on every machine (the real slicer only
# exists in the CI engine container). Writes a minimal gcode file with the two
# comment lines the print-plan parser consumes to whatever path follows -o.
set -eu
out=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "-o" ] || [ "$prev" = "--output" ]; then
    out="$arg"
  fi
  prev="$arg"
done
if [ -z "$out" ]; then
  echo "fake_slicer: no -o output path given" >&2
  exit 2
fi
cat > "$out" <<'GCODE'
; generated by fake_slicer (golden test fixture)
G21
G90
; filament used [g] = 12.50
; estimated printing time (normal mode) = 1h 5m 30s
GCODE
