"""Print-plan generator tests: gcode parsing, no-slicer fallback and a fake slicer."""

import json
import stat
from pathlib import Path

import pytest

from botforge_engine.generators import print_plan
from botforge_engine.generators.base import BuildContext
from botforge_engine.loader import load_registry, load_robot, resolve

REPO_ROOT = Path(__file__).resolve().parents[3]
REGISTRY_DIR = REPO_ROOT / "registry"
TEST_MIN = REPO_ROOT / "robots" / "_test-min"
ROVER = REPO_ROOT / "robots" / "rover-v1"

FAKE_GCODE = """\
; generated by FakeSlicer
; filament used [mm] = 4321.0
; filament used [g] = 12.34
; estimated printing time (normal mode) = 2h 3m
G1 X0 Y0
"""


def _make_ctx(robot_dir: Path, dist_root: Path) -> BuildContext:
    registry = load_registry(REGISTRY_DIR)
    bundle = load_robot(robot_dir)
    resolved = resolve(bundle, registry)
    dist_dir = dist_root / resolved.robot.id
    dist_dir.mkdir(parents=True, exist_ok=True)
    return BuildContext(
        resolved=resolved, robot_dir=robot_dir, dist_dir=dist_dir, registry=registry
    )


# --- parse_gcode_stats -------------------------------------------------------


def test_parse_full_stats_with_days() -> None:
    text = (
        "; filament used [g] = 12.34\n"
        "; estimated printing time (normal mode) = 1d 2h 3m 45s\n"
    )
    stats = print_plan.parse_gcode_stats(text)
    assert stats["grams"] == 12.34
    # 1d 2h 3m 45s = 93825 s -> 1563.75 min -> 1564
    assert stats["minutes"] == 1564


def test_parse_hours_minutes_only() -> None:
    stats = print_plan.parse_gcode_stats(
        "; estimated printing time (normal mode) = 2h 3m\n; filament used [g] = 7.5\n"
    )
    assert stats == {"grams": 7.5, "minutes": 123}


def test_parse_minutes_seconds_rounds() -> None:
    stats = print_plan.parse_gcode_stats(
        "; estimated printing time (normal mode) = 45m 12s\n"
    )
    # 2712 s -> 45.2 min -> 45
    assert stats["minutes"] == 45
    assert stats["grams"] is None


def test_parse_missing_fields_and_total_variant() -> None:
    assert print_plan.parse_gcode_stats("G1 X0\n") == {"grams": None, "minutes": None}
    stats = print_plan.parse_gcode_stats("; total filament used [g] = 99.9\n")
    assert stats == {"grams": 99.9, "minutes": None}


# --- generator without a slicer ---------------------------------------------


def test_run_without_slicer_writes_null_plan(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.delenv("BOTFORGE_PRUSA_SLICER", raising=False)
    monkeypatch.setattr(print_plan.shutil, "which", lambda _name: None)
    ctx = _make_ctx(TEST_MIN, tmp_path)

    print_plan.run(ctx)

    plan = json.loads((ctx.dist_dir / "print" / "print_plan.json").read_text(encoding="utf-8"))
    assert plan["profile"] == "pla-0.20"
    assert plan["estimated"] is False
    assert [p["part_id"] for p in plan["parts"]] == ["plate"]
    part = plan["parts"][0]
    assert part["qty"] == 1
    assert part["grams"] is None
    assert part["minutes"] is None
    assert part["plate_hints"] == {"orientation": "flat", "material": "PLA", "color_role": "body"}
    assert plan["totals"] == {"grams": None, "minutes": None}
    assert (
        "print_plan: prusa-slicer not found — estimates skipped (CI provides it)" in ctx.report
    )


# --- generator with a fake slicer -------------------------------------------


def _write_fake_slicer(tmp_path: Path) -> Path:
    """A stand-in slicer: ignores all args except -o and writes canned gcode there."""
    gcode_file = tmp_path / "canned.gcode"
    gcode_file.write_text(FAKE_GCODE, encoding="utf-8")
    script = tmp_path / "fake-slicer.sh"
    script.write_text(
        "#!/bin/sh\n"
        'out=""\n'
        'prev=""\n'
        'for a in "$@"; do\n'
        '  if [ "$prev" = "-o" ]; then out="$a"; fi\n'
        '  prev="$a"\n'
        "done\n"
        f'if [ -n "$out" ]; then cp "{gcode_file}" "$out"; fi\n'
        "exit 0\n",
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return script


def test_run_with_fake_slicer_parses_and_totals(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("BOTFORGE_PRUSA_SLICER", str(_write_fake_slicer(tmp_path)))
    ctx = _make_ctx(ROVER, tmp_path / "dist")

    # Synthesize STL inputs — the fake slicer never reads them.
    stl_dir = ctx.dist_dir / "cad" / "stl"
    stl_dir.mkdir(parents=True)
    for part in ctx.resolved.printed_parts:
        (stl_dir / f"{part.id}.stl").write_text("solid fake\nendsolid fake\n", encoding="utf-8")

    print_plan.run(ctx)

    plan = json.loads((ctx.dist_dir / "print" / "print_plan.json").read_text(encoding="utf-8"))
    assert plan["estimated"] is True
    parts = {p["part_id"]: p for p in plan["parts"]}
    assert parts["wheel"]["qty"] == 2
    for part in plan["parts"]:
        assert part["grams"] == 12.34
        assert part["minutes"] == 123
    total_qty = sum(p["qty"] for p in plan["parts"])
    assert total_qty == 6  # chassis 1 + wheel 2 + caster_mount 1 + head 1 + lid 1
    assert plan["totals"]["grams"] == round(12.34 * total_qty, 2)
    assert plan["totals"]["minutes"] == 123 * total_qty
    assert ctx.report == []


def test_run_with_fake_slicer_missing_stl_warns(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("BOTFORGE_PRUSA_SLICER", str(_write_fake_slicer(tmp_path)))
    ctx = _make_ctx(TEST_MIN, tmp_path / "dist")  # no cad/stl synthesized

    print_plan.run(ctx)

    plan = json.loads((ctx.dist_dir / "print" / "print_plan.json").read_text(encoding="utf-8"))
    assert plan["estimated"] is True
    assert plan["parts"][0]["grams"] is None
    assert plan["totals"] == {"grams": None, "minutes": None}
    assert any("missing STL for part 'plate'" in msg for msg in ctx.report)
